export const books = [
  {
    id: 1,
    img: "https://images-na.ssl-images-amazon.com/images/I/91bgFzUdDcL._AC_UL200_SR200,200_.jpg",
    title: "Welcome to Kindergaton",
    author: "D.J Steinberg",
    type: "Hardcover",
  },
  {
    id: 2,
    img: "https://images-na.ssl-images-amazon.com/images/I/81eB%2B7%2BCkUL._AC_UL200_SR200,200_.jpg",
    title: "Love you too",
    author: "Amelia Hepworth",
    type: "Paperback",
  },
  {
    id: 3,
    img: "https://images-na.ssl-images-amazon.com/images/I/71KilybDOoL._AC_UL200_SR200,200_.jpg",
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    type: "Hardcover",
  },
  {
    id: 4,
    img: "https://images-na.ssl-images-amazon.com/images/I/71951W96oWL._AC_UL200_SR200,200_.jpg",
    title: "The 48 laws of power",
    author: "Robert Greene",
    type: "Hardcover",
  },
  {
    id: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/81YzHKeWq7L._AC_UL200_SR200,200_.jpg",
    title: "The Midnight Library: A novel",
    author: "Matt Haig",
    type: "Paperback",
  },
  {
    id: 6,
    img: "https://images-na.ssl-images-amazon.com/images/I/51o4b5AdNLL._AC_UL200_SR200,200_.jpg",
    title: "Where's Spot",
    author: "Eric Hill",
    type: "Hardcover",
  },
  {
    id: 7,
    img: "https://images-na.ssl-images-amazon.com/images/I/81GqtNbs%2BPL._AC_UL200_SR200,200_.jpg",
    title: "Billy Summers",
    author: "Stephen King",
    type: "Hardcover",
  },
  {
    id: 8,
    img: "https://images-na.ssl-images-amazon.com/images/I/81BdMSuI5ZS._AC_UL200_SR200,200_.jpg",
    title: "The Last thing he told me: A novel",
    author: "Laura Dave",
    type: "Hardcover",
  },
  {
    id: 9,
    img: "https://images-na.ssl-images-amazon.com/images/I/81TgUz%2B7JBS._AC_UL200_SR200,200_.jpg",
    title: "American Marxism",
    author: "Mark.R.Levin",
    type: "Hardcover",
  },
];
